export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_ADVERTS_REQUEST = 'FETCH_ADVERTS_REQUEST'
export const FETCH_ADVERTS_FAILURE = 'FETCH_ADVERTS_FAILURE'
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS'
export const EDIT_ADVERT = 'EDIT_ADVERT';
export const CREATE_ADVERT = 'CREATE_ADVERT';
export const SET_FILTERS = 'SET_FILTERS';
export const EDIT_SESSION = 'EDIT_SESSION';
export const SET_SESSION = 'SET_SESSION';
export const LOGOUT = 'LOGOUT';

